// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwW6F9vFJJFI9lLApTCQJ3ITN3oYygi68',
    appId: '1:619822349321:ios:37030b95b743a09fa44cd8',
    messagingSenderId: '619822349321',
    projectId: 'pethub-dfdcc',
    storageBucket: 'pethub-dfdcc.firebasestorage.app',
    iosBundleId: 'com.example.adoptionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwW6F9vFJJFI9lLApTCQJ3ITN3oYygi68',
    appId: '1:619822349321:ios:37030b95b743a09fa44cd8',
    messagingSenderId: '619822349321',
    projectId: 'pethub-dfdcc',
    storageBucket: 'pethub-dfdcc.firebasestorage.app',
    iosBundleId: 'com.example.adoptionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-YcY80ipUr8rBPDpq4DKMY-2lP3_OTws',
    appId: '1:619822349321:web:8bf91ce18cfec9d5a44cd8',
    messagingSenderId: '619822349321',
    projectId: 'pethub-dfdcc',
    authDomain: 'pethub-dfdcc.firebaseapp.com',
    storageBucket: 'pethub-dfdcc.firebasestorage.app',
    measurementId: 'G-0HZE7BHSQ4',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-YcY80ipUr8rBPDpq4DKMY-2lP3_OTws',
    appId: '1:619822349321:web:8bf91ce18cfec9d5a44cd8',
    messagingSenderId: '619822349321',
    projectId: 'pethub-dfdcc',
    authDomain: 'pethub-dfdcc.firebaseapp.com',
    storageBucket: 'pethub-dfdcc.firebasestorage.app',
    measurementId: 'G-0HZE7BHSQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBauRVabadndTMwj8AwCt3hzT6NiYwlFtg',
    appId: '1:619822349321:android:e3a8158dde10dca6a44cd8',
    messagingSenderId: '619822349321',
    projectId: 'pethub-dfdcc',
    storageBucket: 'pethub-dfdcc.firebasestorage.app',
  );

}